### ISSUE TITLE
Domoticz switches stop responding after system reboot

### ISSUE THREAD

**Issue by shalwia** [stas-demydiuk/ewpe-smart-mqtt#10]
After system reboots and Docker container with "ewpe-smart-mqtt" stands automatically, the switches created in the Domoticz previously stops responding. The problem may be fixed by click UPDATE button on the "EwpeSmart Air Conditioners via MQTT" hardware item in the Domoticz (each time after system reboots).

**Comment by stas-demydiuk** [comment]
Issue could be that Domoticz starts prior to mqtt and ewpe-smart-mqtt

**Comment by geschriever** [comment]
Have the same issue (without Docker). I have to restart the plugin to get it running.
It seems to be that MQTT is not available yet and the plugin stops.
However a nice plugin! 
Is it also possible to add the functionality to change the temperature?

**Comment by stas-demydiuk** [comment]
@geschriever It is already possible to change the temperature. Try to send such payload
```
{
  "TemUn": 0,
  "SetTem": 22,
  "TemRec": 0
```
It should set temperature to 22.0 by celsius
see https://github.com/tomikaa87/gree-remote#getting-the-current-temperature-reading-from-the-internal-sensor for more info

**Comment by geschriever** [comment]
It is now working okay. Start Domoticz now with a delay of 20 second. It is a command line setting.
