### ISSUE TITLE
The bridge does not find any devices

### ISSUE THREAD

**Issue by wjarka** [stas-demydiuk/ewpe-smart-mqtt#2]
This is all I am getting after running the bridge

2019-02-17T16:47:24.672Z [info]: "Server is listening on 0.0.0.0:56912"

Not sure how to debug what the problem is. Any advice?

**Comment by stas-demydiuk** [comment]
How are you running the bridge, using docker or not?

**Comment by wjarka** [comment]
Without docker. Anything I should pay attention to?

niedz., 17 lut 2019, 20:43: Stanislav Demydiuk <notifications@github.com>
napisał(a):

**Comment by wjarka** [comment]
Actually, it turned out that I had to reset my AC, because for some reason it wasn't visible on my network. Sorry to bother you.
