### ISSUE TITLE
Issue with binding

### ISSUE THREAD

**Issue by Jan-nl** [stas-demydiuk/ewpe-smart-mqtt#22]
After npm start, it's stops at binding. I did look at the older issues and saw the one about the binding, however, it looks like this is a bit different. I use the GREE+ app to control the (Tosot) airco from my Android phone.

After setting the loglevel to debug, I learned the mac address does not seem to bee present;

`2021-08-01T18:09:00.604Z [debug]: Sending request to 192.168.1.73:7000: {mac:,t:bind,uid:0}`

**Comment by Jan-nl** [comment]
Looks I found a solution, for some reason the message.cid is empty after decryption, at least for my Tosot airco.
Updating the device_manager.js around line 109 with
`const deviceId = message.cid || message.mac;` 
gives result

**Comment by stas-demydiuk** [comment]
Thanks, added the fix to the code
