### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by vmv007** [stas-demydiuk/ewpe-smart-mqtt#33]
Hello! Every time when app is opening it asks to turn on bluetooth! Pls fix it!!! 
![Screenshot_20221014-231118_Ewpe Smart](https://user-images.githubusercontent.com/88681489/195934711-1297e33c-d377-4d05-afe7-6f6f3de22b1a.jpg)

**Comment by stas-demydiuk** [comment]
Seems like this issue is not related to the plugin
