### ISSUE TITLE
Missing ewpe-smart-mqtt@1.0.2

### ISSUE THREAD

**Issue by patlas** [stas-demydiuk/ewpe-smart-mqtt#8]
On Raspberry PI 3B+ with raspbian buster (after apt get update).
Manually install node.js:
```
curl -sL https://deb.nodesource.com/setup_13.x | bash -
apt-get install -y nodejs
```
After calling in repository directory: npm install i get:

> npm WARN ewpe-smart-mqtt@1.0.2 No repository field

**Comment by stas-demydiuk** [comment]
This app is not published as NPM package. You can clone it using git
```
git clone https://github.com/stas-demydiuk/ewpe-smart-mqtt
```
