### ISSUE TITLE
standard_init_linux.go:211

### ISSUE THREAD

**Issue by shalwia** [stas-demydiuk/ewpe-smart-mqtt#9]
After starting the **ewpe-smart-mqtt** by **npm start** command it works properly. After setting up the hardware in Domoticz the particular mapped devices can be found in the **Devices** tab.

The problem comes when trying to install ewpe-smart-mqtt by Docker. After pasting the command to run it I'm getting the following response:

`standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size`

Obviously the particular Docker container is not set up.

**Comment by stas-demydiuk** [comment]
On what system are you trying to start docker container?

**Comment by shalwia** [comment]
On that one:
`Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux`

**Comment by stas-demydiuk** [comment]
And what docker image are you trying to use?

**Comment by shalwia** [comment]
The following one:
`REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docker                     latest              26135427427a        3 weeks ago         186MB`

**Comment by stas-demydiuk** [comment]
This one isn't for ARM architecture. Try to use this one `demydiuk/ewpe-smart-mqtt:arm32v6`

**Comment by shalwia** [comment]
Seems it's Docker set up properly using `demydiuk/ewpe-smart-mqtt:arm32v6`
It was running well till the time system has been rebooted. After reboot it doesn't stand up automatically. Should it be like this?
